[package]
name = "kraken"
version = "0.1.0"
edition = "2021"

[lib]
name = "kraken"
path = "src/kraken.rs"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1" }
serde_json = { version = "1" }
